### ISSUE TITLE
Consider to upload to CTAN

### ISSUE THREAD

**Issue by hpreusse** [dgsiegel/latex-tangocolors#1]
Please consider to upload you package to CTAN to make sure it migrates into various TeX distributions, e.g. TeX Live. Thanks!

**Comment by dgsiegel** [comment]
Feel free to go ahead and upload it to CTAN.

**Comment by hpreusse** [comment]
I got a reply from CTAN team:

> However, it needs some more work before we can install it:
> The package should have documentation in PDF format. It should also have a version number, license, and  contact details in the README file.

I stated that the file is LPPL or GPL, however they seem to need a real license file. Could you add it thanks!

**Comment by dgsiegel** [comment]
> Could you add it thanks!

Happy to accept any pull request, but unfortunately I've got no time right now to modify this package.

**Comment by hpreusse** [comment]
I've created pull request #2, consider to apply it.

**Comment by hpreusse** [comment]
I got further input from the CTAN team:

> Such a construction of "upstream author" vs. "uploader" (= maintainer of the CTAN package) rather complicates matters for us.
> 
> It would be preferable if "upstream" uploaded themselves, so that we could talk to them directly, of if _you_ had write permission for the package (maybe make a fork?).
> 
> At least the relation of "upstream author" and "maintainer of the CTAN package" should be made clear in  the documentation.
> 
So I would prefer, if _you_ could upload the package to CTAN. The upload form is [not complicated](https://www.ctan.org/upload/), so the upload could be done within minutes. The package should should be prepared so far. Don't forget to remove the .gitignore file from the uploaded zip file. Thanks!

**Comment by dgsiegel** [comment]
Well, we could do that, but I could also give you write access to this repo? That way you could be a maintainer of this package.

**Comment by hpreusse** [comment]
If that would be an option for you...go ahead.

**Comment by dgsiegel** [comment]
Sure thing, just sent out an invite.

**Comment by hpreusse** [comment]
I made some changes and submitted another upload.

**Comment by dgsiegel** [comment]
Awesome, thanks!
